name: Build release

on:
  push:
    tags:
      - "*"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.x'

      - name: Install dependencies
        run: |
          sudo apt-get install libgl1-mesa-dev xorg-dev -y
          sudo apt-get install gcc-mingw-w64 gcc-multilib -y

      - name: Build program
        run: |
          make

      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '/.github/* /.git/* .gitignore go.* *.go README.md'
          path: '.'
          directory: '.'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset as zip
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: "release.zip"
          asset_content_type: application/zip